[package]
name = "migration"
version = "0.1.0"
edition = "2021"

[lib]
name = "migration"
path = "src/lib.rs"

[dependencies]
sea-schema = { version = "^0.5", default-features = false, features = [ "migration", "debug-print" ] }
entity = { path = "../repo/entity" }