[package]
name = "personal-manager"
version = "0.1.0"
edition = "2021"
authors = ["Igor Merkushev <geek.space@ya.ru>"]

[workspace]
members = [".", "app_config", "repository", "tasks", "util", "migration", "domain", "application", "remote", "integration_tests"]