[app]
name = "assets"
port = "8000"
host = "0.0.0.0"
version = "0.1.0"
debug = false

[vk]
client_id = ""
secret_key = ""
access_token = ""
group_id = ""
hour = 7
minute = 5

[db]
url = "postgres://postgres:postgres@127.0.0.1/assets"

[aws]
secret_access_key = "wJalrXUtnFEMIK7MDENGbPxRfiCYEXAMPLEKEY"
access_key_id = "AKIAIOSFODNN7EXAMPLE"
region = "us-east-1"
endpoint = "http://127.0.0.1:9000"
bucket = "assets"
